-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.diagnosticos
(
    dx_id integer NOT NULL,
    tipo_dx character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT diagnosticos_pkey PRIMARY KEY (dx_id)
);

CREATE TABLE IF NOT EXISTS public.medicos
(
    medico_id integer NOT NULL,
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    sexo character varying(1) COLLATE pg_catalog."default" NOT NULL,
    "años_experiencia" integer NOT NULL,
    "años_institucion" integer NOT NULL,
    universidad character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT medicos_pkey PRIMARY KEY (medico_id)
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    paciente_id integer NOT NULL,
    turno_id integer NOT NULL,
    dx_id integer NOT NULL,
    salida_id integer NOT NULL,
    hora_ingreso time without time zone NOT NULL,
    hora_egreso time without time zone NOT NULL,
    laboratorios boolean NOT NULL,
    imagenes boolean NOT NULL,
    interconsulta boolean NOT NULL,
    edad integer NOT NULL,
    sexo boolean NOT NULL,
    triage integer NOT NULL,
    CONSTRAINT pacientes_pkey PRIMARY KEY (paciente_id)
);

CREATE TABLE IF NOT EXISTS public.salidas
(
    salida_id integer NOT NULL,
    tipo_salida character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT salidas_pkey PRIMARY KEY (salida_id)
);

CREATE TABLE IF NOT EXISTS public.turnos
(
    turno_id integer NOT NULL,
    medico_id integer NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_final time without time zone NOT NULL,
    fecha date NOT NULL,
    n_pacientes integer NOT NULL,
    CONSTRAINT turnos_pkey PRIMARY KEY (turno_id)
);

ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT dx_fk FOREIGN KEY (dx_id)
    REFERENCES public.diagnosticos (dx_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_p
    ON public.pacientes(dx_id);


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT salidas_fk FOREIGN KEY (salida_id)
    REFERENCES public.salidas (salida_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_salidas_fk
    ON public.pacientes(salida_id);


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT turnos_fk FOREIGN KEY (turno_id)
    REFERENCES public.turnos (turno_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_turnos_fk
    ON public.pacientes(turno_id);


ALTER TABLE IF EXISTS public.turnos
    ADD CONSTRAINT medico_fk FOREIGN KEY (medico_id)
    REFERENCES public.medicos (medico_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_medico_fk
    ON public.turnos(medico_id);

END;